name: ✨ Feat
description: 새로운 기능 또는 작업 단위를 정의합니다.
title: "[FEAT] "
labels: ["feature"]
assignees: []

body:
  - type: textarea
    attributes:
      label: Describe
      description: 어떤 기능/작업인지 한 줄로 설명해주세요.
      placeholder: 예) 버튼 공통 컴포넌트 추가
    validations:
      required: true

  - type: textarea
    attributes:
      label: Tasks
      description: 구현해야 할 작업을 체크리스트 형태로 작성해주세요.
      placeholder: |
        - [ ] 
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Scope
      description: 변경이 발생하는 영역을 선택해주세요.
      options:
        - label: Frontend
        - label: Backend
        - label: AI / Data
        - label: Infra / DevOps
        - label: Docs
        - label: Global