name: 🚨 Fix
description: 버그 및 오류를 해결합니다.
title: "[FIX] "
labels: ["bug"]
assignees: []

body:
  - type: textarea
    attributes:
      label: Describe
      description: 어떤 문제가 발생했는지 간략하게 설명해주세요.
      placeholder: 예) 로그인 시 토큰이 저장되지 않는 문제
    validations:
      required: true

  - type: textarea
    attributes:
      label: Fix Plan
      description: 어떤 방식으로 수정할 예정인지 작성해주세요.
      placeholder: 
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Scope
      description: 변경이 발생하는 영역을 선택해주세요
      options:
        - label: Frontend
        - label: Backend
        - label: AI / Data
        - label: Infra / DevOps
        - label: Docs
        - label: Global
