export const queryKeys = {
  me: ['me'] as const,
  blockedSingers: ['me', 'blocked-singers'] as const,
  blockedSongs: ['me', 'blocked-songs'] as const,
  searchMusic: (q: string) => ['music', 'search', q] as const,
  searchSingers: (q: string) => ['singers', 'search', q] as const,
  randomSingers: (gender: string) => ['singers', 'random', gender] as const,
  folders: ['library', 'folders'] as const,
  wishlist: (folderId?: string) => ['library', 'wishlist', folderId ?? 'all'] as const,
  history: ['library', 'history'] as const,
  buskingRooms: ['busking', 'rooms'] as const,
  buskingRoom: (roomId: string) => ['busking', 'rooms', roomId] as const,
  buskingResult: (roomId: string) => ['busking', 'rooms', roomId, 'result'] as const,
  myBuskingHistory: ['busking', 'me', 'history'] as const,
  analysisJob: (jobId: string) => ['analysis', 'jobs', jobId] as const,
  vocalProfile: ['analysis', 'profile'] as const,
  homeFeeds: ['home', 'feeds'] as const,
  recommendationArchive: (params?: { genre?: string; keyword?: string; date?: string }) =>
    ['archive', 'recommendation', params] as const,
};
