/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 소셜 로그인 (카카오 / 네이버)
         * @description 프론트엔드가 발급받은 OAuth 액세스 토큰을 전달하면, 사용자 정보를 조회하고 우리 서비스 JWT를 발급합니다.
         */
        post: operations["social_login_api_v1_auth_login__provider__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 갱신 (RTR)
         * @description Authorization 헤더에 리프레시 토큰을 담아 보내면, 기존 토큰을 폐기하고 새 토큰 쌍을 발급합니다.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원 탈퇴
         * @description 현재 로그인된 사용자를 탈퇴 처리합니다.
         */
        post: operations["withdraw_api_v1_auth_withdraw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 정보 조회
         * @description 현재 로그인된 사용자의 정보를 반환합니다. 캐시된 보컬 분석 정보(vocal_summary)도 포함됩니다.
         */
        get: operations["get_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 프로필 수정 */
        patch: operations["update_profile_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/users/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 설정 변경 (JSONB 부분 업데이트)
         * @description 전달된 키만 기존 settings에 머지합니다. 예: `{"push_enabled": false}` → push_enabled만 변경.
         */
        patch: operations["update_settings_api_v1_users_me_settings_patch"];
        trace?: never;
    };
    "/api/v1/music/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Music */
        get: operations["search_music_api_v1_music_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Folders
         * @description 사용자의 모든 폴더 조회 (아이템 개수 포함)
         */
        get: operations["get_folders_api_v1_library_folders_get"];
        put?: never;
        /**
         * Create Folder
         * @description 새 폴더 생성
         */
        post: operations["create_folder_api_v1_library_folders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/folders/{folder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Folder
         * @description 폴더 삭제 (시스템 폴더는 삭제 불가)
         */
        delete: operations["delete_folder_api_v1_library_folders__folder_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/wishlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Wishlist
         * @description 위시리스트 아이템 조회
         */
        get: operations["get_wishlist_api_v1_library_wishlist_get"];
        put?: never;
        /**
         * Add Wishlist Item
         * @description 위시리스트에 곡 추가
         */
        post: operations["add_wishlist_item_api_v1_library_wishlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/wishlist/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Wishlist Item
         * @description 위시리스트 아이템 삭제
         */
        delete: operations["delete_wishlist_item_api_v1_library_wishlist__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History
         * @description 부른 노래 기록 조회
         */
        get: operations["get_history_api_v1_library_history_get"];
        put?: never;
        /**
         * Create History
         * @description 부른 노래 기록 저장
         */
        post: operations["create_history_api_v1_library_history_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/history/{archive_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete History
         * @description 부른 노래 기록 삭제
         */
        delete: operations["delete_history_api_v1_library_history__archive_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update History
         * @description 부른 노래 기록 수정 (태그, 메모)
         */
        patch: operations["update_history_api_v1_library_history__archive_id__patch"];
        trace?: never;
    };
    "/api/v1/busking/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rooms
         * @description 현재 라이브 중이거나 준비 중인 방 목록 조회
         */
        get: operations["get_rooms_api_v1_busking_rooms_get"];
        put?: never;
        /**
         * Create Room
         * @description 버스킹 방 생성 (로그인 필수)
         */
        post: operations["create_room_api_v1_busking_rooms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/test/kakao/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kakao Login
         * @description 카카오 로그인 페이지로 리다이렉트
         */
        get: operations["kakao_login_auth_test_kakao_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/test/kakao/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kakao Callback
         * @description 카카오 콜백 → 인가코드로 토큰 교환 → JWT 발급 → 테스트 페이지로 리다이렉트
         */
        get: operations["kakao_callback_auth_test_kakao_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArchiveCreate */
        ArchiveCreate: {
            /**
             * Song Id
             * Format: uuid
             */
            song_id: string;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Memo */
            memo?: string | null;
        };
        /** ArchiveResponse */
        ArchiveResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            song?: components["schemas"]["ArchiveSongInfo"] | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** Memo */
            memo?: string | null;
            /**
             * Recorded Date
             * Format: date-time
             */
            recorded_date: string;
        };
        /** ArchiveSongInfo */
        ArchiveSongInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Album Cover */
            album_cover?: string | null;
        };
        /** ArchiveUpdate */
        ArchiveUpdate: {
            /** Tags */
            tags?: string[] | null;
            /** Memo */
            memo?: string | null;
        };
        /** BuskingRoomCreate */
        BuskingRoomCreate: {
            /** Title */
            title: string;
            /** Thumbnail */
            thumbnail?: string | null;
        };
        /** BuskingRoomResponse */
        BuskingRoomResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Host Id
             * Format: uuid
             */
            host_id: string;
            /** Title */
            title: string;
            /** Thumbnail */
            thumbnail: string | null;
            /** Status */
            status: string;
            /** Total Viewers */
            total_viewers: number;
            /** Started At */
            started_at: string | null;
        };
        /** FolderCreate */
        FolderCreate: {
            /** Name */
            name: string;
        };
        /** FolderResponse */
        FolderResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string;
            /** Is System */
            is_system: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Item Count
             * @default 0
             */
            item_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginResponse
         * @description POST /auth/login/{provider} 응답
         */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Is New User */
            is_new_user: boolean;
        };
        /**
         * SettingsUpdateRequest
         * @description PATCH /users/me/settings 요청 - JSONB 부분 업데이트
         */
        SettingsUpdateRequest: {
            /** Push Enabled */
            push_enabled?: boolean | null;
            /** Marketing Agree */
            marketing_agree?: boolean | null;
        };
        /**
         * SocialLoginRequest
         * @description POST /auth/login/{provider} 요청
         */
        SocialLoginRequest: {
            /**
             * Access Token
             * @description OAuth 제공자 액세스 토큰
             */
            access_token: string;
            /**
             * Fcm Token
             * @description FCM 디바이스 토큰 (푸시알림)
             */
            fcm_token?: string | null;
        };
        /**
         * TokenResponse
         * @description 토큰 응답 (공통)
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UserResponse
         * @description GET /users/me 응답 - 보컬 캐시 포함
         */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nickname */
            nickname: string;
            /** Email */
            email?: string | null;
            /** Profile Img */
            profile_img?: string | null;
            /** Provider */
            provider: string;
            /** Vocal Summary */
            vocal_summary?: Record<string, never> | null;
            /** Settings */
            settings: Record<string, never>;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * UserUpdateRequest
         * @description PATCH /users/me 요청
         */
        UserUpdateRequest: {
            /** Nickname */
            nickname?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WishlistItemCreate */
        WishlistItemCreate: {
            /**
             * Song Id
             * Format: uuid
             */
            song_id: string;
            /** Folder Id */
            folder_id?: string | null;
        };
        /** WishlistItemResponse */
        WishlistItemResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Folder Id */
            folder_id?: string | null;
            song: components["schemas"]["WishlistSongInfo"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** WishlistSongInfo */
        WishlistSongInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Album Cover */
            album_cover?: string | null;
        };
        /**
         * WithdrawRequest
         * @description POST /auth/withdraw 요청
         */
        WithdrawRequest: {
            /**
             * Reason
             * @description 탈퇴 사유
             */
            reason?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    social_login_api_v1_auth_login__provider__post: {
        parameters: {
            query: {
                args: unknown;
                kwargs: unknown;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocialLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query: {
                args: unknown;
                kwargs: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    withdraw_api_v1_auth_withdraw_post: {
        parameters: {
            query: {
                args: unknown;
                kwargs: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WithdrawRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_users_me_get: {
        parameters: {
            query: {
                args: unknown;
                kwargs: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_api_v1_users_me_patch: {
        parameters: {
            query: {
                args: unknown;
                kwargs: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_api_v1_users_me_settings_patch: {
        parameters: {
            query: {
                args: unknown;
                kwargs: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_music_api_v1_music_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_folders_api_v1_library_folders_get: {
        parameters: {
            query: {
                args: unknown;
                kwargs: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_folder_api_v1_library_folders_post: {
        parameters: {
            query: {
                args: unknown;
                kwargs: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_folder_api_v1_library_folders__folder_id__delete: {
        parameters: {
            query: {
                args: unknown;
                kwargs: unknown;
            };
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wishlist_api_v1_library_wishlist_get: {
        parameters: {
            query: {
                /** @description 폴더 ID (없으면 전체) */
                folder_id?: string | null;
                /** @description 정렬 기준 (LATEST) */
                sort?: string;
                args: unknown;
                kwargs: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_wishlist_item_api_v1_library_wishlist_post: {
        parameters: {
            query: {
                args: unknown;
                kwargs: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WishlistItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_wishlist_item_api_v1_library_wishlist__item_id__delete: {
        parameters: {
            query: {
                args: unknown;
                kwargs: unknown;
            };
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_api_v1_library_history_get: {
        parameters: {
            query: {
                /** @description 태그 필터 (예: AGAIN, HIGH_PITCH) */
                tag?: string | null;
                args: unknown;
                kwargs: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_history_api_v1_library_history_post: {
        parameters: {
            query: {
                args: unknown;
                kwargs: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_history_api_v1_library_history__archive_id__delete: {
        parameters: {
            query: {
                args: unknown;
                kwargs: unknown;
            };
            header?: never;
            path: {
                archive_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_history_api_v1_library_history__archive_id__patch: {
        parameters: {
            query: {
                args: unknown;
                kwargs: unknown;
            };
            header?: never;
            path: {
                archive_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rooms_api_v1_busking_rooms_get: {
        parameters: {
            query: {
                args: unknown;
                kwargs: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuskingRoomResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_room_api_v1_busking_rooms_post: {
        parameters: {
            query: {
                args: unknown;
                kwargs: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuskingRoomCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuskingRoomResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kakao_login_auth_test_kakao_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    kakao_callback_auth_test_kakao_callback_get: {
        parameters: {
            query: {
                code: string;
                args: unknown;
                kwargs: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
